using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace DonutCountyAP.Randomizer;

public enum CheckId : long
{
    // TODO: chunked check ids
    None,
    // ability items
    HoleWater = 1000,
    HoleFire,
    HoleSnake,
    HoleLight,
    HoleBunnies,
    // catapult check
    Catapult = 2000,
    // catapult items
    CatapultBoxes,
    CatapultChickens,
    CatapultEggs,
    CatapultHoneycomb,
    CatapultFrogs,
    CatapultWaterBalloons,
    CatapultWater,
    CatapultDonutsCamerasRaccoons,
    CatapultHackingDevice,
    CatapultBombs,
    // level collection item
    Fragment = 3000, // TODO: better name
    // filler/trap items
    FillerBackflip,
    TrapConcrete,
    TrapDepths,
    // delivery locations
    DeliverMirasHouse = 4000,
    DeliverPottersRock,
    DeliverRangerStation,
    DeliverRiverbed,
    DeliverCampground,
    DeliverHopperSprings,
    DeliverJoshuaTree,
    DeliverBeachLotC,
    DeliverGeckoPark,
    DeliverChickenBarn,
    DeliverHoneyNutForest,
    DeliverCatSoup,
    DeliverDonutShop,
    DeliverAbandonedHouse,
    DeliverRaccoonLagoon,
    DeliverThe405,
    DeliverRaccoonHQ,
    DeliverBiologyLab,
    DeliverAnthropologyLab,
    DeliverTrashKingsOffice,
    DeliverBossFight,
    // segment locations
    SegmentMirasHouse1 = 5000,
    SegmentPottersRock1,
    SegmentPottersRock2,
    SegmentPottersRock3,
    SegmentPottersRock4,
    SegmentPottersRock5,
    SegmentRangerStation1,
    SegmentRangerStation2,
    SegmentRangerStation3,
    SegmentRiverbed1,
    SegmentCampground1,
    SegmentCampground2,
    SegmentHopperSprings1,
    SegmentHopperSprings2,
    SegmentHopperSprings3,
    SegmentHopperSprings4,
    SegmentJoshuaTree1,
    SegmentBeachLotC1,
    SegmentBeachLotC2,
    SegmentBeachLotC3,
    SegmentGeckoPark1,
    SegmentGeckoPark2,
    SegmentChickenBarn1,
    SegmentChickenBarn2,
    SegmentChickenBarn3,
    SegmentChickenBarn4,
    SegmentChickenBarn5,
    SegmentHoneyNutForest1,
    SegmentHoneyNutForest2,
    SegmentCatSoup1,
    SegmentCatSoup2,
    SegmentCatSoup3,
    SegmentCatSoup4,
    SegmentDonutShop1,
    SegmentAbandonedHouse1,
    SegmentAbandonedHouse2,
    SegmentRaccoonLagoon1,
    SegmentRaccoonLagoon2,
    SegmentRaccoonLagoon3,
    SegmentRaccoonLagoon4,
    SegmentThe4051,
    SegmentThe4052,
    SegmentThe4053,
    SegmentThe4054,
    SegmentRaccoonHQ1,
    SegmentRaccoonHQ2,
    SegmentRaccoonHQ3,
    SegmentBiologyLab1,
    SegmentBiologyLab2,
    SegmentBiologyLab3,
    SegmentAnthroplogyLab1,
    SegmentAnthroplogyLab2,
    SegmentAnthroplogyLab3,
    SegmentTrashKingsOffice1,
    SegmentTrashKingsOffice2,
    SegmentTrashKingsOffice3,
    SegmentBossFight1,
    SegmentBossFight2,
    // other logic things
    SnakeDanger1 = 6000, // Progressive Snake Danger
    SnakeDanger2,
    SnakeDanger3,
    SnakeDanger4,
    Salt1, // Progressive Salt
    Salt2,
    Pepper1, // Progressive Pepper
    Pepper2,
    Pepper3,
    HackProtocol,
    // achievement locations
    AchievementBandit = 7000,
    AchievementSecretSoup,
    AchievementGameOver,
    AchievementDisrespecter,
    AchievementQuackEnthusiast,
    AchievementEggBreaker,
    AchievementMusicLover,
    AchievementFlawless,
    AchievementDethroner,
    AchievementBossFight,
    AchievementHacker,
    AchievementTheFlumeIsDoomed,
    AchievementDonutCounty,
    AchievementGamer,
    AchievementPyro,
    AchievementPupsOddyssey,
}
