# generated by autologic.fsx
from BaseClasses import ItemClassification
from rule_builder.options import OptionFilter
from rule_builder.rules import Has, True_
from . import options

LOCATION_NAME_TO_ID = {
    "Mira's House: Donut County": 22,
    "Mira's House": 1,
    "Potter's Rock: Pile": 23,
    "Potter's Rock: Front": 24,
    "Potter's Rock: Potter": 25,
    "Potter's Rock: Pots": 26,
    "Potter's Rock: Launch": 27,
    "Potter's Rock": 2,
    "Ranger Station: Snakes": 28,
    "Ranger Station: Snake hole": 29,
    "Snake danger: Snake": 98,
    "Snake danger: Horn": 99,
    "Snake danger: Sign": 100,
    "Snake danger: Swing": 101,
    "Ranger Station: Snake danger": 30,
    "Ranger Station": 3,
    "Riverbed: Small Dog": 31,
    "Riverbed": 4,
    "Campground: Popcorn": 32,
    "Campground: Right tent": 33,
    "Campground": 5,
    "Hopper Springs: Carrots": 34,
    "Hopper Springs: Bunnies 1": 35,
    "Hopper Springs: Bunnies 2": 36,
    "Hopper Springs: Bunnies 3": 37,
    "Hopper Springs": 6,
    "Joshua Tree: Arson": 38,
    "Joshua Tree": 7,
    "Beach Lot C: First firework": 39,
    "Beach Lot C: Birds": 40,
    "Beach Lot C: Cliff": 41,
    "Beach Lot C": 8,
    "Gecko Park: Geckos": 42,
    "Gecko Park: Coco": 43,
    "Gecko Park": 9,
    "Chicken Barn: Boxes": 44,
    "Buy Catapult": 97,
    "Chicken Barn: BK's apartment": 45,
    "Chicken Barn: Catapult tutorial": 46,
    "Chicken Barn: Chicken toss": 47,
    "Chicken Barn: Egg toss": 48,
    "Chicken Barn": 10,
    "Honey Nut Forest: Get frog": 49,
    "Honey Nut Forest: Frog tutorial": 50,
    "Honey Nut Forest": 11,
    "Cat Soup: Outside": 51,
    "Salt 1": 102,
    "Salt 2": 103,
    "Pepper 1": 104,
    "Pepper 2": 105,
    "Pepper 3": 106,
    "Cat Soup: Cooking": 52,
    "Cat Soup: Dining": 53,
    "Cat Soup: Cars": 54,
    "Cat Soup": 12,
    "Donut Shop: Car": 55,
    "Donut Shop": 13,
    "Abandoned House: Dark": 56,
    "Abandoned House: Light": 57,
    "Abandoned house": 14,
    "Raccoon Lagoon: Water wheel": 58,
    "Raccoon Lagoon: Log flume": 59,
    "Raccoon Lagoon: Dispenser": 60,
    "Raccoon Lagoon: Ferris wheel": 61,
    "Racoon Lagoon": 15,
    "The 405: Small car": 62,
    "The 405: Truck repair": 63,
    "The 405: Cop raccoons": 64,
    "The 405: Big boy": 65,
    "The 405": 16,
    "Raccoon HQ: Exterior": 66,
    "Raccoon HQ: USB drive": 67,
    "H.A.C.K. Protocol": 68,
    "Raccoon HQ: Hacking complete": 69,
    "Raccoon HQ": 17,
    "Biology Lab: Raccoons": 70,
    "Biology Lab: Snake": 71,
    "Biology Lab: Lab": 72,
    "Biology Lab": 18,
    "Anthropology Lab: Garbage bin": 73,
    "Anthropology Lab: Fire alarm": 74,
    "Anthropology Lab: Firework": 75,
    "Anthropology Lab": 19,
    "Trash King's Office: Donuts 1": 76,
    "Trash King's Office: Donuts 2": 77,
    "Trash King's Office: Donuts 3": 78,
    "Trash King's Office": 20,
    "Boss Fight: Phase 1": 79,
    "Boss Fight: Phase 2": 80,
    "Boss Fight": 21,
    "Achievement: Bandit": 81,
    "Achievement: Secret Soup": 82,
    "Achievement: Game Over": 83,
    "Achievement: Disrespecter": 84,
    "Achievement: Quack Enthusiast": 85,
    "Achievement: Egg Breaker": 86,
    "Achievement: Music Lover": 87,
    "Achievement: Flawless": 88,
    "Achievement: Dethroner": 89,
    "Achievement: Boss Fight": 90,
    "Achievement: Hacker": 91,
    "Achievement: The Flume Is Doomed": 92,
    "Achievement: Donut County": 93,
    "Achievement: Gamer": 94,
    "Achievement: Pyro": 95,
    "Achievement: Pup's Oddyssey": 96,
}
LOCATION_SORT_ORDER = {
    "Mira's House: Donut County": "d00c0z",
    "Mira's House": "d00c1z",
    "Potter's Rock: Pile": "d01c0z",
    "Potter's Rock: Front": "d01c1z",
    "Potter's Rock: Potter": "d01c2z",
    "Potter's Rock: Pots": "d01c3z",
    "Potter's Rock: Launch": "d01c4z",
    "Potter's Rock": "d01c5z",
    "Ranger Station: Snakes": "d02c0z",
    "Ranger Station: Snake hole": "d02c1z",
    "Snake danger: Snake": "d02c2s0",
    "Snake danger: Horn": "d02c2s1",
    "Snake danger: Sign": "d02c2s2",
    "Snake danger: Swing": "d02c2s3",
    "Ranger Station: Snake danger": "d02c2z",
    "Ranger Station": "d02c3z",
    "Riverbed: Small Dog": "d03c0z",
    "Riverbed": "d03c1z",
    "Campground: Popcorn": "d04c0z",
    "Campground: Right tent": "d04c1z",
    "Campground": "d04c2z",
    "Hopper Springs: Carrots": "d05c0z",
    "Hopper Springs: Bunnies 1": "d05c1z",
    "Hopper Springs: Bunnies 2": "d05c2z",
    "Hopper Springs: Bunnies 3": "d05c3z",
    "Hopper Springs": "d05c4z",
    "Joshua Tree: Arson": "d06c0z",
    "Joshua Tree": "d06c1z",
    "Beach Lot C: First firework": "d07c0z",
    "Beach Lot C: Birds": "d07c1z",
    "Beach Lot C: Cliff": "d07c2z",
    "Beach Lot C": "d07c3z",
    "Gecko Park: Geckos": "d08c0z",
    "Gecko Park: Coco": "d08c1z",
    "Gecko Park": "d08c2z",
    "Chicken Barn: Boxes": "d09c0z",
    "Buy Catapult": "d09c1s1",
    "Chicken Barn: BK's apartment": "d09c1z",
    "Chicken Barn: Catapult tutorial": "d09c2z",
    "Chicken Barn: Chicken toss": "d09c3z",
    "Chicken Barn: Egg toss": "d09c4z",
    "Chicken Barn": "d09c5z",
    "Honey Nut Forest: Get frog": "d10c0z",
    "Honey Nut Forest: Frog tutorial": "d10c1z",
    "Honey Nut Forest": "d10c2z",
    "Cat Soup: Outside": "d11c0z",
    "Salt 1": "d11c1s0",
    "Salt 2": "d11c1s1",
    "Pepper 1": "d11c1s2",
    "Pepper 2": "d11c1s3",
    "Pepper 3": "d11c1s4",
    "Cat Soup: Cooking": "d11c1z",
    "Cat Soup: Dining": "d11c2z",
    "Cat Soup: Cars": "d11c3z",
    "Cat Soup": "d11c4z",
    "Donut Shop: Car": "d12c0z",
    "Donut Shop": "d12c1z",
    "Abandoned House: Dark": "d13c0z",
    "Abandoned House: Light": "d13c1z",
    "Abandoned house": "d13c2z",
    "Raccoon Lagoon: Water wheel": "d14c0z",
    "Raccoon Lagoon: Log flume": "d14c1z",
    "Raccoon Lagoon: Dispenser": "d14c2z",
    "Raccoon Lagoon: Ferris wheel": "d14c3z",
    "Racoon Lagoon": "d14c4z",
    "The 405: Small car": "d15c0z",
    "The 405: Truck repair": "d15c1z",
    "The 405: Cop raccoons": "d15c2z",
    "The 405: Big boy": "d15c3z",
    "The 405": "d15c4z",
    "Raccoon HQ: Exterior": "d16c0z",
    "Raccoon HQ: USB drive": "d16c1z",
    "H.A.C.K. Protocol": "d16c2s0",
    "Raccoon HQ: Hacking complete": "d16c2z",
    "Raccoon HQ": "d16c3z",
    "Biology Lab: Raccoons": "d17c0z",
    "Biology Lab: Snake": "d17c1z",
    "Biology Lab: Lab": "d17c2z",
    "Biology Lab": "d17c3z",
    "Anthropology Lab: Garbage bin": "d18c0z",
    "Anthropology Lab: Fire alarm": "d18c1z",
    "Anthropology Lab: Firework": "d18c2z",
    "Anthropology Lab": "d18c3z",
    "Trash King's Office: Donuts 1": "d19c0z",
    "Trash King's Office: Donuts 2": "d19c1z",
    "Trash King's Office: Donuts 3": "d19c2z",
    "Trash King's Office": "d19c3z",
    "Boss Fight: Phase 1": "d20c0z",
    "Boss Fight: Phase 2": "d20c1z",
    "Boss Fight": "d20c2z",
    "Achievement: Bandit": "d17c3a0",
    "Achievement: Secret Soup": "d11c1a0",
    "Achievement: Game Over": "d20c0a0",
    "Achievement: Disrespecter": "d18c1a0",
    "Achievement: Quack Enthusiast": "d00c0a0",
    "Achievement: Egg Breaker": "d09c4a0",
    "Achievement: Music Lover": "d08c2a0",
    "Achievement: Flawless": "d20c1a0",
    "Achievement: Dethroner": "d20c2a0",
    "Achievement: Boss Fight": "d20c2a1",
    "Achievement: Hacker": "d16c2a0",
    "Achievement: The Flume Is Doomed": "d14c4a0",
    "Achievement: Donut County": "d12c1a0",
    "Achievement: Gamer": "d09c1a0",
    "Achievement: Pyro": "d06c0a0",
    "Achievement: Pup's Oddyssey": "d01c5s0",
}
LEVEL_ENTRANCES = [
    ("MirasHouse0", "Mira's House"),
    ("PottersRock0", "Potter's Rock"),
    ("RangerStation0", "Ranger Station"),
    ("Riverbed0", "Riverbed"),
    ("Campground0", "Campground"),
    ("HopperSprings0", "Hopper Springs"),
    ("JoshuaTree0", "Joshua Tree"),
    ("BeachLotC0", "Beach Lot C"),
    ("GeckoPark0", "Gecko Park"),
    ("ChickenBarn0", "Chicken Barn"),
    ("HoneyNutForest0", "Honey Nut Forest"),
    ("CatSoup0", "Cat Soup"),
    ("DonutShop0", "Donut Shop"),
    ("AbandonedHouse0", "Abandoned House"),
    ("RaccoonLagoon0", "Raccoon Lagoon"),
    ("The4050", "The 405"),
    ("RaccoonHQ0", "Raccoon HQ"),
    ("BiologyLab0", "Biology Lab"),
    ("AnthropologyLab0", "Anthropology Lab"),
    ("TrashKingsOffice0", "Trash King's Office"),
    ("BossFight0", "Boss Fight"),
    ("Aftermath0", None),
]
ITEM_NAME_TO_ID = {
    "Hole: Water": 1,
    "Hole: Fire": 2,
    "Hole: Snake": 3,
    "Hole: Light": 4,
    "Hole: Bunnies": 22,
    "Catapult": 5,
    "Catapult: Boxes": 6,
    "Catapult: Chickens": 7,
    "Catapult: Eggs": 8,
    "Catapult: Honeycomb": 9,
    "Catapult: Frogs": 10,
    "Catapult: Water, Balloons, and Fish": 11,
    "Catapult: Donuts and Cameras": 12,
    "Catapult: Raccoons": 45,
    "Catapult: Hacking Device": 13,
    "Catapult: Keycards": 46,
    "Catapult: Bombs": 14,
    "Quadcopter Piece": 15,
    "BK Does One (1) Backflip": 16,
    "Concrete Trap": 17,
    "999ft Below Trap": 23,
    "Progressive Snake Danger": 18,
    "Progressive Salt": 19,
    "Progressive Pepper": 20,
    "H.A.C.K. Protocol": 21,
    "Mira's House": 24,
    "Potter's Rock": 25,
    "Ranger Station": 26,
    "Riverbed": 27,
    "Campground": 28,
    "Hopper Springs": 29,
    "Joshua Tree": 30,
    "Beach Lot C": 31,
    "Gecko Park": 32,
    "Chicken Barn": 33,
    "Honey Nut Forest": 34,
    "Cat Soup": 35,
    "Donut Shop": 36,
    "Abandoned House": 37,
    "Raccoon Lagoon": 38,
    "The 405": 39,
    "Raccoon HQ": 40,
    "Biology Lab": 41,
    "Anthropology Lab": 42,
    "Trash King's Office": 43,
    "Boss Fight": 44,
}
ITEM_DATA = {
    "Hole: Water": (ItemClassification.progression | ItemClassification.useful, [OptionFilter(options.HoleWater, options.HoleWater.option_true)]),
    "Hole: Fire": (ItemClassification.progression | ItemClassification.useful, [OptionFilter(options.HoleFire, options.HoleFire.option_true)]),
    "Hole: Snake": (ItemClassification.progression | ItemClassification.useful, [OptionFilter(options.HoleSnake, options.HoleSnake.option_true)]),
    "Hole: Light": (ItemClassification.progression | ItemClassification.useful, [OptionFilter(options.HoleLight, options.HoleLight.option_true)]),
    "Hole: Bunnies": (ItemClassification.progression | ItemClassification.useful, [OptionFilter(options.HoleBunnies, options.HoleBunnies.option_true)]),
    "Catapult": (ItemClassification.progression | ItemClassification.useful, [OptionFilter(options.Catapult, options.Catapult.option_global)]),
    "Catapult: Boxes": (ItemClassification.progression | ItemClassification.useful, [OptionFilter(options.Catapult, options.Catapult.option_split)]),
    "Catapult: Chickens": (ItemClassification.progression | ItemClassification.useful, [OptionFilter(options.Catapult, options.Catapult.option_split)]),
    "Catapult: Eggs": (ItemClassification.progression | ItemClassification.useful, [OptionFilter(options.Catapult, options.Catapult.option_split)]),
    "Catapult: Honeycomb": (ItemClassification.progression | ItemClassification.useful, [OptionFilter(options.Catapult, options.Catapult.option_split)]),
    "Catapult: Frogs": (ItemClassification.progression | ItemClassification.useful, [OptionFilter(options.Catapult, options.Catapult.option_split)]),
    "Catapult: Water, Balloons, and Fish": (ItemClassification.progression | ItemClassification.useful, [OptionFilter(options.Catapult, options.Catapult.option_split)]),
    "Catapult: Donuts and Cameras": (ItemClassification.progression | ItemClassification.useful, [OptionFilter(options.Catapult, options.Catapult.option_split)]),
    "Catapult: Raccoons": (ItemClassification.progression | ItemClassification.useful, [OptionFilter(options.Catapult, options.Catapult.option_split)]),
    "Catapult: Hacking Device": (ItemClassification.progression | ItemClassification.useful, [OptionFilter(options.Catapult, options.Catapult.option_split)]),
    "Catapult: Keycards": (ItemClassification.progression | ItemClassification.useful, [OptionFilter(options.Catapult, options.Catapult.option_split)]),
    "Catapult: Bombs": (ItemClassification.progression | ItemClassification.useful, [OptionFilter(options.Catapult, options.Catapult.option_split)]),
    "Quadcopter Piece": (ItemClassification.progression, []),
    "BK Does One (1) Backflip": (ItemClassification.filler, []),
    "Concrete Trap": (ItemClassification.trap, []),
    "999ft Below Trap": (ItemClassification.trap, []),
    "Progressive Snake Danger": (ItemClassification.progression | ItemClassification.useful, [OptionFilter(options.SnakeDanger, options.SnakeDanger.option_true)]),
    "Progressive Salt": (ItemClassification.progression | ItemClassification.useful, [OptionFilter(options.SaltAndPepper, options.SaltAndPepper.option_true)]),
    "Progressive Pepper": (ItemClassification.progression | ItemClassification.useful, [OptionFilter(options.SaltAndPepper, options.SaltAndPepper.option_true)]),
    "H.A.C.K. Protocol": (ItemClassification.progression | ItemClassification.useful, [OptionFilter(options.HackProtocol, options.HackProtocol.option_true)]),
    "Mira's House": (ItemClassification.progression | ItemClassification.useful, [OptionFilter(options.Levels, options.Levels.option_true)]),
    "Potter's Rock": (ItemClassification.progression | ItemClassification.useful, [OptionFilter(options.Levels, options.Levels.option_true)]),
    "Ranger Station": (ItemClassification.progression | ItemClassification.useful, [OptionFilter(options.Levels, options.Levels.option_true)]),
    "Riverbed": (ItemClassification.progression | ItemClassification.useful, [OptionFilter(options.Levels, options.Levels.option_true)]),
    "Campground": (ItemClassification.progression | ItemClassification.useful, [OptionFilter(options.Levels, options.Levels.option_true)]),
    "Hopper Springs": (ItemClassification.progression | ItemClassification.useful, [OptionFilter(options.Levels, options.Levels.option_true)]),
    "Joshua Tree": (ItemClassification.progression | ItemClassification.useful, [OptionFilter(options.Levels, options.Levels.option_true)]),
    "Beach Lot C": (ItemClassification.progression | ItemClassification.useful, [OptionFilter(options.Levels, options.Levels.option_true)]),
    "Gecko Park": (ItemClassification.progression | ItemClassification.useful, [OptionFilter(options.Levels, options.Levels.option_true)]),
    "Chicken Barn": (ItemClassification.progression | ItemClassification.useful, [OptionFilter(options.Levels, options.Levels.option_true)]),
    "Honey Nut Forest": (ItemClassification.progression | ItemClassification.useful, [OptionFilter(options.Levels, options.Levels.option_true)]),
    "Cat Soup": (ItemClassification.progression | ItemClassification.useful, [OptionFilter(options.Levels, options.Levels.option_true)]),
    "Donut Shop": (ItemClassification.progression | ItemClassification.useful, [OptionFilter(options.Levels, options.Levels.option_true)]),
    "Abandoned House": (ItemClassification.progression | ItemClassification.useful, [OptionFilter(options.Levels, options.Levels.option_true)]),
    "Raccoon Lagoon": (ItemClassification.progression | ItemClassification.useful, [OptionFilter(options.Levels, options.Levels.option_true)]),
    "The 405": (ItemClassification.progression | ItemClassification.useful, [OptionFilter(options.Levels, options.Levels.option_true)]),
    "Raccoon HQ": (ItemClassification.progression | ItemClassification.useful, [OptionFilter(options.Levels, options.Levels.option_true)]),
    "Biology Lab": (ItemClassification.progression | ItemClassification.useful, [OptionFilter(options.Levels, options.Levels.option_true)]),
    "Anthropology Lab": (ItemClassification.progression | ItemClassification.useful, [OptionFilter(options.Levels, options.Levels.option_true)]),
    "Trash King's Office": (ItemClassification.progression | ItemClassification.useful, [OptionFilter(options.Levels, options.Levels.option_true)]),
    "Boss Fight": (ItemClassification.progression | ItemClassification.useful, [OptionFilter(options.Levels, options.Levels.option_true)]),
}
ITEM_FILLER = {
    "filler": "BK Does One (1) Backflip",
    "concrete_trap": "Concrete Trap",
    "depths_trap": "999ft Below Trap",
}
    
def HasFlag(name: str, amount: int = 1):
    return Has(name, amount, options=ITEM_DATA[name][1], filtered_resolution=True)

def regions(f):
    f("MirasHouse0", "Menu", True_())
    f("PottersRock0", "Menu", True_())
    f("RangerStation0", "Menu", True_())
    f("Riverbed0", "Menu", True_())
    f("Campground0", "Menu", True_())
    f("HopperSprings0", "Menu", True_())
    f("JoshuaTree0", "Menu", True_())
    f("BeachLotC0", "Menu", True_())
    f("GeckoPark0", "Menu", True_())
    f("ChickenBarn0", "Menu", True_())
    f("HoneyNutForest0", "Menu", True_())
    f("CatSoup0", "Menu", True_())
    f("DonutShop0", "Menu", True_())
    f("AbandonedHouse0", "Menu", True_())
    f("RaccoonLagoon0", "Menu", True_())
    f("The4050", "Menu", True_())
    f("RaccoonHQ0", "Menu", True_())
    f("BiologyLab0", "Menu", True_())
    f("AnthropologyLab0", "Menu", True_())
    f("TrashKingsOffice0", "Menu", True_())
    f("BossFight0", "Menu", True_())
    f("MirasHouse1", "MirasHouse0", True_())
    f("MirasHouse2", "MirasHouse1", True_())
    f("PottersRock1", "PottersRock0", True_())
    f("PottersRock2", "PottersRock1", True_())
    f("PottersRock3", "PottersRock2", True_())
    f("PottersRock4", "PottersRock3", True_())
    f("PottersRock5", "PottersRock4", HasFlag("Hole: Fire"))
    f("PottersRock6", "PottersRock5", True_())
    f("RangerStation1", "RangerStation0", True_())
    f("RangerStation2", "RangerStation1", True_())
    f("RangerStation3", "RangerStation2", HasFlag("Hole: Snake") & HasFlag("Progressive Snake Danger", 4))
    f("RangerStation4", "RangerStation3", True_())
    f("Riverbed1", "Riverbed0", True_())
    f("Riverbed2", "Riverbed1", HasFlag("Hole: Water"))
    f("Campground1", "Campground0", True_())
    f("Campground2", "Campground1", HasFlag("Hole: Fire"))
    f("Campground3", "Campground2", True_())
    f("HopperSprings1", "HopperSprings0", True_())
    f("HopperSprings2", "HopperSprings1", HasFlag("Hole: Bunnies"))
    f("HopperSprings3", "HopperSprings2", True_())
    f("HopperSprings4", "HopperSprings3", True_())
    f("HopperSprings5", "HopperSprings4", True_())
    f("JoshuaTree1", "JoshuaTree0", HasFlag("Hole: Fire"))
    f("JoshuaTree2", "JoshuaTree1", True_())
    f("BeachLotC1", "BeachLotC0", HasFlag("Hole: Fire"))
    f("BeachLotC2", "BeachLotC1", True_())
    f("BeachLotC3", "BeachLotC2", True_())
    f("BeachLotC4", "BeachLotC3", True_())
    f("GeckoPark1", "GeckoPark0", True_())
    f("GeckoPark2", "GeckoPark1", True_())
    f("GeckoPark3", "GeckoPark2", True_())
    f("ChickenBarn1", "ChickenBarn0", True_())
    f("ChickenBarn2", "ChickenBarn1", True_())
    f("ChickenBarn3", "ChickenBarn2", HasFlag("Catapult") & HasFlag("Catapult: Boxes"))
    f("ChickenBarn4", "ChickenBarn3", HasFlag("Catapult") & HasFlag("Catapult: Chickens"))
    f("ChickenBarn5", "ChickenBarn4", HasFlag("Catapult") & HasFlag("Catapult: Eggs"))
    f("ChickenBarn6", "ChickenBarn5", True_())
    f("HoneyNutForest1", "HoneyNutForest0", HasFlag("Catapult") & HasFlag("Catapult: Honeycomb"))
    f("HoneyNutForest2", "HoneyNutForest1", HasFlag("Catapult") & HasFlag("Catapult: Frogs"))
    f("HoneyNutForest3", "HoneyNutForest2", True_())
    f("CatSoup1", "CatSoup0", True_())
    f("CatSoup2", "CatSoup1", HasFlag("Hole: Water") & HasFlag("Progressive Salt") & HasFlag("Progressive Pepper"))
    f("CatSoup3", "CatSoup2", True_())
    f("CatSoup4", "CatSoup3", True_())
    f("CatSoup5", "CatSoup4", True_())
    f("DonutShop1", "DonutShop0", True_())
    f("DonutShop2", "DonutShop1", True_())
    f("AbandonedHouse1", "AbandonedHouse0", HasFlag("Hole: Light"))
    f("AbandonedHouse2", "AbandonedHouse1", True_())
    f("AbandonedHouse3", "AbandonedHouse2", True_())
    f("RaccoonLagoon1", "RaccoonLagoon0", HasFlag("Hole: Water") & HasFlag("Catapult") & HasFlag("Catapult: Water, Balloons, and Fish"))
    f("RaccoonLagoon2", "RaccoonLagoon1", True_())
    f("RaccoonLagoon3", "RaccoonLagoon2", True_())
    f("RaccoonLagoon4", "RaccoonLagoon3", True_())
    f("RaccoonLagoon5", "RaccoonLagoon4", True_())
    f("The4051", "The4050", True_())
    f("The4052", "The4051", True_())
    f("The4053", "The4052", HasFlag("Catapult") & HasFlag("Catapult: Donuts and Cameras") & HasFlag("Catapult") & HasFlag("Catapult: Raccoons"))
    f("The4054", "The4053", True_())
    f("The4055", "The4054", True_())
    f("RaccoonHQ1", "RaccoonHQ0", True_())
    f("RaccoonHQ2", "RaccoonHQ1", True_())
    f("RaccoonHQ3", "RaccoonHQ2", HasFlag("Catapult") & HasFlag("Catapult: Hacking Device") & HasFlag("H.A.C.K. Protocol"))
    f("RaccoonHQ4", "RaccoonHQ3", HasFlag("Catapult") & HasFlag("Catapult: Keycards"))
    f("BiologyLab1", "BiologyLab0", True_())
    f("BiologyLab2", "BiologyLab1", HasFlag("Hole: Snake"))
    f("BiologyLab3", "BiologyLab2", HasFlag("Catapult") & HasFlag("Catapult: Frogs") & HasFlag("Hole: Bunnies"))
    f("BiologyLab4", "BiologyLab3", HasFlag("Catapult") & HasFlag("Catapult: Keycards"))
    f("AnthropologyLab1", "AnthropologyLab0", True_())
    f("AnthropologyLab2", "AnthropologyLab1", HasFlag("Hole: Fire"))
    f("AnthropologyLab3", "AnthropologyLab2", HasFlag("Hole: Water"))
    f("AnthropologyLab4", "AnthropologyLab3", True_())
    f("TrashKingsOffice1", "TrashKingsOffice0", True_())
    f("TrashKingsOffice2", "TrashKingsOffice1", True_())
    f("TrashKingsOffice3", "TrashKingsOffice2", True_())
    f("TrashKingsOffice4", "TrashKingsOffice3", True_())
    f("BossFight1", "BossFight0", HasFlag("Catapult") & HasFlag("Catapult: Bombs"))
    f("BossFight2", "BossFight1", HasFlag("Catapult") & HasFlag("Catapult: Hacking Device"))
    f("BossFight3", "BossFight2", True_())

def locations(o, f):
    if o.level_segments:
        f(22, "Mira's House: Donut County", "MirasHouse1", True_())
        f(23, "Potter's Rock: Pile", "PottersRock1", True_())
        f(24, "Potter's Rock: Front", "PottersRock2", True_())
        f(25, "Potter's Rock: Potter", "PottersRock3", True_())
        f(26, "Potter's Rock: Pots", "PottersRock4", True_())
        f(27, "Potter's Rock: Launch", "PottersRock5", HasFlag("Hole: Fire"))
        f(28, "Ranger Station: Snakes", "RangerStation1", True_())
        f(29, "Ranger Station: Snake hole", "RangerStation2", True_())
        f(30, "Ranger Station: Snake danger", "RangerStation3", HasFlag("Hole: Snake") & HasFlag("Progressive Snake Danger", 4))
        f(31, "Riverbed: Small Dog", "Riverbed1", True_())
        f(32, "Campground: Popcorn", "Campground1", True_())
        f(33, "Campground: Right tent", "Campground2", HasFlag("Hole: Fire"))
        f(34, "Hopper Springs: Carrots", "HopperSprings1", True_())
        f(35, "Hopper Springs: Bunnies 1", "HopperSprings2", HasFlag("Hole: Bunnies"))
        f(36, "Hopper Springs: Bunnies 2", "HopperSprings3", True_())
        f(37, "Hopper Springs: Bunnies 3", "HopperSprings4", True_())
        f(38, "Joshua Tree: Arson", "JoshuaTree1", HasFlag("Hole: Fire"))
        f(39, "Beach Lot C: First firework", "BeachLotC1", HasFlag("Hole: Fire"))
        f(40, "Beach Lot C: Birds", "BeachLotC2", True_())
        f(41, "Beach Lot C: Cliff", "BeachLotC3", True_())
        f(42, "Gecko Park: Geckos", "GeckoPark1", True_())
        f(43, "Gecko Park: Coco", "GeckoPark2", True_())
        f(44, "Chicken Barn: Boxes", "ChickenBarn1", True_())
        f(45, "Chicken Barn: BK's apartment", "ChickenBarn2", True_())
        f(46, "Chicken Barn: Catapult tutorial", "ChickenBarn3", HasFlag("Catapult") & HasFlag("Catapult: Boxes"))
        f(47, "Chicken Barn: Chicken toss", "ChickenBarn4", HasFlag("Catapult") & HasFlag("Catapult: Chickens"))
        f(48, "Chicken Barn: Egg toss", "ChickenBarn5", HasFlag("Catapult") & HasFlag("Catapult: Eggs"))
        f(49, "Honey Nut Forest: Get frog", "HoneyNutForest1", HasFlag("Catapult") & HasFlag("Catapult: Honeycomb"))
        f(50, "Honey Nut Forest: Frog tutorial", "HoneyNutForest2", HasFlag("Catapult") & HasFlag("Catapult: Frogs"))
        f(51, "Cat Soup: Outside", "CatSoup1", True_())
        f(52, "Cat Soup: Cooking", "CatSoup2", HasFlag("Hole: Water") & HasFlag("Progressive Salt") & HasFlag("Progressive Pepper"))
        f(53, "Cat Soup: Dining", "CatSoup3", True_())
        f(54, "Cat Soup: Cars", "CatSoup4", True_())
        f(55, "Donut Shop: Car", "DonutShop1", True_())
        f(56, "Abandoned House: Dark", "AbandonedHouse1", HasFlag("Hole: Light"))
        f(57, "Abandoned House: Light", "AbandonedHouse2", True_())
        f(58, "Raccoon Lagoon: Water wheel", "RaccoonLagoon1", HasFlag("Hole: Water") & HasFlag("Catapult") & HasFlag("Catapult: Water, Balloons, and Fish"))
        f(59, "Raccoon Lagoon: Log flume", "RaccoonLagoon2", True_())
        f(60, "Raccoon Lagoon: Dispenser", "RaccoonLagoon3", True_())
        f(61, "Raccoon Lagoon: Ferris wheel", "RaccoonLagoon4", True_())
        f(62, "The 405: Small car", "The4051", True_())
        f(63, "The 405: Truck repair", "The4052", True_())
        f(64, "The 405: Cop raccoons", "The4053", HasFlag("Catapult") & HasFlag("Catapult: Donuts and Cameras") & HasFlag("Catapult") & HasFlag("Catapult: Raccoons"))
        f(65, "The 405: Big boy", "The4054", True_())
        f(66, "Raccoon HQ: Exterior", "RaccoonHQ1", True_())
        f(67, "Raccoon HQ: USB drive", "RaccoonHQ2", True_())
        f(69, "Raccoon HQ: Hacking complete", "RaccoonHQ3", HasFlag("Catapult") & HasFlag("Catapult: Hacking Device") & HasFlag("H.A.C.K. Protocol"))
        f(70, "Biology Lab: Raccoons", "BiologyLab1", True_())
        f(71, "Biology Lab: Snake", "BiologyLab2", HasFlag("Hole: Snake"))
        f(72, "Biology Lab: Lab", "BiologyLab3", HasFlag("Catapult") & HasFlag("Catapult: Frogs") & HasFlag("Hole: Bunnies"))
        f(73, "Anthropology Lab: Garbage bin", "AnthropologyLab1", True_())
        f(74, "Anthropology Lab: Fire alarm", "AnthropologyLab2", HasFlag("Hole: Fire"))
        f(75, "Anthropology Lab: Firework", "AnthropologyLab3", HasFlag("Hole: Water"))
        f(76, "Trash King's Office: Donuts 1", "TrashKingsOffice1", True_())
        f(77, "Trash King's Office: Donuts 2", "TrashKingsOffice2", True_())
        f(78, "Trash King's Office: Donuts 3", "TrashKingsOffice3", True_())
        f(79, "Boss Fight: Phase 1", "BossFight1", HasFlag("Catapult") & HasFlag("Catapult: Bombs"))
        f(80, "Boss Fight: Phase 2", "BossFight2", HasFlag("Catapult") & HasFlag("Catapult: Hacking Device"))
    if True:
        f(1, "Mira's House", "MirasHouse2", True_())
        f(2, "Potter's Rock", "PottersRock6", True_())
        f(3, "Ranger Station", "RangerStation4", True_())
        f(4, "Riverbed", "Riverbed2", HasFlag("Hole: Water"))
        f(5, "Campground", "Campground3", True_())
        f(6, "Hopper Springs", "HopperSprings5", True_())
        f(7, "Joshua Tree", "JoshuaTree2", True_())
        f(8, "Beach Lot C", "BeachLotC4", True_())
        f(9, "Gecko Park", "GeckoPark3", True_())
        f(10, "Chicken Barn", "ChickenBarn6", True_())
        f(11, "Honey Nut Forest", "HoneyNutForest3", True_())
        f(12, "Cat Soup", "CatSoup5", True_())
        f(13, "Donut Shop", "DonutShop2", True_())
        f(14, "Abandoned house", "AbandonedHouse3", True_())
        f(15, "Racoon Lagoon", "RaccoonLagoon5", True_())
        f(16, "The 405", "The4055", True_())
        f(17, "Raccoon HQ", "RaccoonHQ4", HasFlag("Catapult") & HasFlag("Catapult: Keycards"))
        f(18, "Biology Lab", "BiologyLab4", HasFlag("Catapult") & HasFlag("Catapult: Keycards"))
        f(19, "Anthropology Lab", "AnthropologyLab4", True_())
        f(20, "Trash King's Office", "TrashKingsOffice4", True_())
        f(21, "Boss Fight", "BossFight3", True_())
    if o.snake_danger:
        f(98, "Snake danger: Snake", "RangerStation2", HasFlag("Hole: Snake"))
        f(99, "Snake danger: Horn", "RangerStation2", HasFlag("Hole: Snake"))
        f(100, "Snake danger: Sign", "RangerStation2", HasFlag("Hole: Snake"))
        f(101, "Snake danger: Swing", "RangerStation2", HasFlag("Hole: Snake"))
    if o.buy_catapult:
        f(97, "Buy Catapult", "ChickenBarn1", True_())
    if o.salt_and_pepper:
        f(102, "Salt 1", "CatSoup1", HasFlag("Hole: Water"))
        f(103, "Salt 2", "CatSoup1", HasFlag("Hole: Water"))
        f(104, "Pepper 1", "CatSoup1", HasFlag("Hole: Water"))
        f(105, "Pepper 2", "CatSoup1", HasFlag("Hole: Water"))
        f(106, "Pepper 3", "CatSoup1", HasFlag("Hole: Water"))
    if o.hack_protocol:
        f(68, "H.A.C.K. Protocol", "RaccoonHQ2", True_())
    if o.achievements:
        f(81, "Achievement: Bandit", "BiologyLab4", True_())
        f(82, "Achievement: Secret Soup", "CatSoup1", HasFlag("Hole: Water") & HasFlag("Progressive Salt", 2) & HasFlag("Progressive Pepper", 3))
        f(83, "Achievement: Game Over", "BossFight0", True_())
        f(84, "Achievement: Disrespecter", "AnthropologyLab1", True_())
        f(85, "Achievement: Quack Enthusiast", "Menu", HasFlag("Mira's House") | HasFlag("Gecko Park") | HasFlag("Chicken Barn") | HasFlag("Raccoon HQ"))
        f(86, "Achievement: Egg Breaker", "ChickenBarn4", True_())
        f(87, "Achievement: Music Lover", "GeckoPark3", True_())
        f(88, "Achievement: Flawless", "BossFight2", True_())
        f(89, "Achievement: Dethroner", "BossFight3", True_())
        f(90, "Achievement: Boss Fight", "BossFight3", True_())
        f(91, "Achievement: Hacker", "RaccoonHQ3", True_())
        f(92, "Achievement: The Flume Is Doomed", "RaccoonLagoon5", True_())
        f(93, "Achievement: Donut County", "DonutShop2", True_())
        f(94, "Achievement: Gamer", "ChickenBarn1", True_())
        f(95, "Achievement: Pyro", "JoshuaTree1", True_())
        f(96, "Achievement: Pup's Oddyssey", "PottersRock5", True_())

def items(o, f):
    if ITEM_DATA["Hole: Water"][1][0].check(o):
        f(1, "Hole: Water")
    if ITEM_DATA["Hole: Fire"][1][0].check(o):
        f(1, "Hole: Fire")
    if ITEM_DATA["Hole: Snake"][1][0].check(o):
        f(1, "Hole: Snake")
    if ITEM_DATA["Hole: Light"][1][0].check(o):
        f(1, "Hole: Light")
    if ITEM_DATA["Hole: Bunnies"][1][0].check(o):
        f(1, "Hole: Bunnies")
    if ITEM_DATA["Catapult"][1][0].check(o):
        f(1, "Catapult")
    if ITEM_DATA["Catapult: Boxes"][1][0].check(o):
        f(1, "Catapult: Boxes")
        f(1, "Catapult: Chickens")
        f(1, "Catapult: Eggs")
        f(1, "Catapult: Honeycomb")
        f(1, "Catapult: Frogs")
        f(1, "Catapult: Water, Balloons, and Fish")
        f(1, "Catapult: Donuts and Cameras")
        f(1, "Catapult: Raccoons")
        f(1, "Catapult: Hacking Device")
        f(1, "Catapult: Keycards")
        f(1, "Catapult: Bombs")
    f(0, "Quadcopter Piece")
    f(0, "BK Does One (1) Backflip")
    f(0, "Concrete Trap")
    f(0, "999ft Below Trap")
    if ITEM_DATA["Progressive Snake Danger"][1][0].check(o):
        f(4, "Progressive Snake Danger")
    if ITEM_DATA["Progressive Salt"][1][0].check(o):
        f(2, "Progressive Salt")
        f(3, "Progressive Pepper")
    if ITEM_DATA["H.A.C.K. Protocol"][1][0].check(o):
        f(1, "H.A.C.K. Protocol")
    if ITEM_DATA["Mira's House"][1][0].check(o):
        f(1, "Mira's House")
        f(1, "Potter's Rock")
        f(1, "Ranger Station")
        f(1, "Riverbed")
        f(1, "Campground")
        f(1, "Hopper Springs")
        f(1, "Joshua Tree")
        f(1, "Beach Lot C")
        f(1, "Gecko Park")
        f(1, "Chicken Barn")
        f(1, "Honey Nut Forest")
        f(1, "Cat Soup")
        f(1, "Donut Shop")
        f(1, "Abandoned House")
        f(1, "Raccoon Lagoon")
        f(1, "The 405")
        f(1, "Raccoon HQ")
        f(1, "Biology Lab")
        f(1, "Anthropology Lab")
        f(1, "Trash King's Office")
        f(1, "Boss Fight")
